{
  "errorStackTrace": "org.bonitasoft.engine.commons.exceptions.SBonitaRuntimeException: java.lang.Exception: Human Failed task 2",
  "connectorInstanceId": "100045",
  "errorMessage": "Human Failed task"
}
