{
  "errorStackTrace": "org.bonitasoft.engine.commons.exceptions.SBonitaRuntimeException: java.lang.Exception: Human Failed task",
  "connectorInstanceId": "100029",
  "errorMessage": "Human Failed task"
}